#!/bin/bash
cat /etc/network/interfaces | grep dns-nameservers > /etc/resolv.conf
sed -i 's/dns-nameservers/nameserver/g' /etc/resolv.conf
sed -i 's/^[ \t]*//' /etc/resolv.conf
echo 'search wbstraining.intern' >> /etc/resolv.conf